name: Rust CI

on:
  push:
    branches:
      - main

permissions:
  contents: write  # リポジトリのコンテンツへの書き込み権限を付与


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run cargo test
        run: cargo test --verbose

      - name: Build project
        run: cargo build --release
      
      # 新しいフォルダを作成し、生成物をコピー
      - name: Copy build artifacts to new folder
        run: |
          mkdir -p artifacts
          cp -r target/release/* artifacts/

    # 生成物（例: target/releaseディレクトリ）をデプロイ用のブランチにコピー
      - name: Deploy to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GamingChikuwabu"
          git config --global user.email "k.56482525@gmail.com"
          
          # 無視されているファイルを強制的に追加
          git add -f target/release/*

          # 変更があればコミット
          git diff --quiet || git commit -m "Add build artifacts"

          # mainブランチにプッシュ
          git push origin main
